fuck

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -26,6 +26,8 @@ jobs:
 
             APP_DIR="$HOME/app/${REPO_NAME}"
             REPO_URL="https://github.com/${OWNER}/${REPO_NAME}.git"
+            SERVICE_FILE="${REPO_NAME}.service"
+            SYSTEMD_USER_DIR="$HOME/.config/systemd/user"
 
             PB_DIR="$HOME/storage/pocketbase"
 
@@ -74,6 +76,19 @@ jobs:
                 cp -ru ./pb_hooks/* "$PB_DIR/pb_hooks/"
             fi
 
-            ./pocketbase superuser create ${SU_EMAIL} ${SU_PASSWORD} || true
-            ./pocketbase service install --http="127.0.0.1:8090" --dir="$PB_DIR"
-            ./pocketbase service restart
+            ./pocketbase update
+            ./pocketbase superuser upsert ${SU_EMAIL} ${SU_PASSWORD} || true
+
+            mkdir -p "$SYSTEMD_USER_DIR"
+            ln -sf "$APP_DIR/$SERVICE_FILE" "$SYSTEMD_USER_DIR/$SERVICE_FILE"
+
+            systemctl --user daemon-reload
+            systemctl --user enable ${REPO_NAME}
+            systemctl --user restart ${REPO_NAME}
+
+            if systemctl --user is-active --quiet ${REPO_NAME}; then
+                echo "✅ Deployment Successful and Bot is Running!"
+            else
+                echo "❌ Deployment Failed: Bot is not running."
+                systemctl --user status ${REPO_NAME}
+            fi
